[package]
name = 'mokshya-raffle'
version = '1.0.0'


[addresses]
raffle = "_"
Std = "0x1"
aptos_std = "0x1"
[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework"}
AptosToken = { local = "../../aptos-core/aptos-move/framework/aptos-token" }
AptosStdlib = { local = "../../aptos-core/aptos-move/framework/aptos-stdlib" }
